# Generated by Django 3.0 on 2019-12-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='twitter_users',
            new_name='TwitterUsers',
        ),
    ]
